# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MachineLearningPrediction.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MachineLearningPrediction(object):
    def setupUi(self, MachineLearningPrediction):
        MachineLearningPrediction.setObjectName("MachineLearningPrediction")
        MachineLearningPrediction.resize(1440, 855)
        self.mlp_frame = QtWidgets.QFrame(MachineLearningPrediction)
        self.mlp_frame.setGeometry(QtCore.QRect(420, 60, 461, 531))
        self.mlp_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.mlp_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.mlp_frame.setObjectName("mlp_frame")
        self.label_6 = QtWidgets.QLabel(self.mlp_frame)
        self.label_6.setGeometry(QtCore.QRect(20, 10, 231, 16))
        self.label_6.setObjectName("label_6")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.mlp_frame)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(40, 50, 391, 441))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.plot_prediction = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.plot_prediction.setContentsMargins(0, 0, 0, 0)
        self.plot_prediction.setObjectName("plot_prediction")
        self.files_frame = QtWidgets.QFrame(MachineLearningPrediction)
        self.files_frame.setGeometry(QtCore.QRect(20, 240, 401, 91))
        self.files_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.files_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.files_frame.setObjectName("files_frame")
        self.label_load = QtWidgets.QLabel(self.files_frame)
        self.label_load.setGeometry(QtCore.QRect(10, 20, 76, 16))
        self.label_load.setObjectName("label_load")
        self.btn_load_file = QtWidgets.QPushButton(self.files_frame)
        self.btn_load_file.setGeometry(QtCore.QRect(120, 10, 271, 32))
        self.btn_load_file.setObjectName("btn_load_file")
        self.btn_start_prediction = QtWidgets.QPushButton(self.files_frame)
        self.btn_start_prediction.setGeometry(QtCore.QRect(180, 50, 131, 32))
        self.btn_start_prediction.setObjectName("btn_start_prediction")
        self.random_forest_frame = QtWidgets.QFrame(MachineLearningPrediction)
        self.random_forest_frame.setGeometry(QtCore.QRect(890, 60, 481, 531))
        self.random_forest_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.random_forest_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.random_forest_frame.setObjectName("random_forest_frame")
        self.label_9 = QtWidgets.QLabel(self.random_forest_frame)
        self.label_9.setGeometry(QtCore.QRect(10, 10, 271, 16))
        self.label_9.setObjectName("label_9")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.random_forest_frame)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(30, 50, 411, 441))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.plot_confusion_matrix = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.plot_confusion_matrix.setContentsMargins(0, 0, 0, 0)
        self.plot_confusion_matrix.setObjectName("plot_confusion_matrix")
        self.table_widget = QtWidgets.QTableWidget(MachineLearningPrediction)
        self.table_widget.setGeometry(QtCore.QRect(20, 460, 401, 291))
        self.table_widget.setMinimumSize(QtCore.QSize(401, 0))
        self.table_widget.setMaximumSize(QtCore.QSize(401, 16777215))
        self.table_widget.setObjectName("table_widget")
        self.table_widget.setColumnCount(4)
        self.table_widget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget.setHorizontalHeaderItem(3, item)
        self.label_8 = QtWidgets.QLabel(MachineLearningPrediction)
        self.label_8.setGeometry(QtCore.QRect(20, 430, 271, 16))
        self.label_8.setObjectName("label_8")
        self.files_frame_2 = QtWidgets.QFrame(MachineLearningPrediction)
        self.files_frame_2.setGeometry(QtCore.QRect(20, 110, 401, 101))
        self.files_frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.files_frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.files_frame_2.setObjectName("files_frame_2")
        self.label_load_2 = QtWidgets.QLabel(self.files_frame_2)
        self.label_load_2.setGeometry(QtCore.QRect(20, 20, 81, 16))
        self.label_load_2.setObjectName("label_load_2")
        self.btn_load_model = QtWidgets.QPushButton(self.files_frame_2)
        self.btn_load_model.setGeometry(QtCore.QRect(120, 10, 271, 32))
        self.btn_load_model.setObjectName("btn_load_model")
        self.txt_model_name = QtWidgets.QLineEdit(self.files_frame_2)
        self.txt_model_name.setGeometry(QtCore.QRect(120, 50, 261, 21))
        self.txt_model_name.setObjectName("txt_model_name")
        self.label_11 = QtWidgets.QLabel(MachineLearningPrediction)
        self.label_11.setGeometry(QtCore.QRect(20, 220, 271, 16))
        self.label_11.setObjectName("label_11")
        self.label_10 = QtWidgets.QLabel(MachineLearningPrediction)
        self.label_10.setGeometry(QtCore.QRect(20, 50, 91, 16))
        self.label_10.setObjectName("label_10")
        self.btn_data_open = QtWidgets.QPushButton(MachineLearningPrediction)
        self.btn_data_open.setGeometry(QtCore.QRect(10, 10, 221, 32))
        self.btn_data_open.setObjectName("btn_data_open")
        self.btn_ml_prediction_open = QtWidgets.QPushButton(MachineLearningPrediction)
        self.btn_ml_prediction_open.setGeometry(QtCore.QRect(450, 10, 251, 32))
        self.btn_ml_prediction_open.setObjectName("btn_ml_prediction_open")
        self.btn_ml_open = QtWidgets.QPushButton(MachineLearningPrediction)
        self.btn_ml_open.setGeometry(QtCore.QRect(220, 10, 241, 32))
        self.btn_ml_open.setObjectName("btn_ml_open")
        self.label_13 = QtWidgets.QLabel(MachineLearningPrediction)
        self.label_13.setGeometry(QtCore.QRect(20, 390, 91, 16))
        self.label_13.setObjectName("label_13")
        self.txt_feature_size = QtWidgets.QLineEdit(MachineLearningPrediction)
        self.txt_feature_size.setGeometry(QtCore.QRect(150, 390, 91, 21))
        self.txt_feature_size.setText("")
        self.txt_feature_size.setClearButtonEnabled(False)
        self.txt_feature_size.setObjectName("txt_feature_size")
        self.radioCNN = QtWidgets.QRadioButton(MachineLearningPrediction)
        self.radioCNN.setGeometry(QtCore.QRect(20, 80, 100, 20))
        self.radioCNN.setObjectName("radioCNN")
        self.radioMLP = QtWidgets.QRadioButton(MachineLearningPrediction)
        self.radioMLP.setGeometry(QtCore.QRect(110, 80, 100, 20))
        self.radioMLP.setObjectName("radioMLP")
        self.btn_prediction_distance_open = QtWidgets.QPushButton(MachineLearningPrediction)
        self.btn_prediction_distance_open.setGeometry(QtCore.QRect(700, 10, 251, 32))
        self.btn_prediction_distance_open.setObjectName("btn_prediction_distance_open")
        self.cb_output = QtWidgets.QComboBox(MachineLearningPrediction)
        self.cb_output.setGeometry(QtCore.QRect(150, 350, 251, 26))
        self.cb_output.setObjectName("cb_output")
        self.label_load_3 = QtWidgets.QLabel(MachineLearningPrediction)
        self.label_load_3.setGeometry(QtCore.QRect(30, 350, 76, 16))
        self.label_load_3.setObjectName("label_load_3")

        self.retranslateUi(MachineLearningPrediction)
        QtCore.QMetaObject.connectSlotsByName(MachineLearningPrediction)

    def retranslateUi(self, MachineLearningPrediction):
        _translate = QtCore.QCoreApplication.translate
        MachineLearningPrediction.setWindowTitle(_translate("MachineLearningPrediction", "MachineLearningPrediction"))
        self.label_6.setText(_translate("MachineLearningPrediction", "Prediction"))
        self.label_load.setText(_translate("MachineLearningPrediction", "Select File"))
        self.btn_load_file.setText(_translate("MachineLearningPrediction", "Load Files"))
        self.btn_start_prediction.setText(_translate("MachineLearningPrediction", "Start Prediction"))
        self.label_9.setText(_translate("MachineLearningPrediction", "Confusion Matrix"))
        item = self.table_widget.horizontalHeaderItem(0)
        item.setText(_translate("MachineLearningPrediction", "Label"))
        item = self.table_widget.horizontalHeaderItem(1)
        item.setText(_translate("MachineLearningPrediction", "Total"))
        self.label_8.setText(_translate("MachineLearningPrediction", "Prediction Table"))
        self.label_load_2.setText(_translate("MachineLearningPrediction", "Select Model"))
        self.btn_load_model.setText(_translate("MachineLearningPrediction", "Load Model"))
        self.label_11.setText(_translate("MachineLearningPrediction", "Load Prediction Files"))
        self.label_10.setText(_translate("MachineLearningPrediction", "Load Model"))
        self.btn_data_open.setText(_translate("MachineLearningPrediction", "Data Processing"))
        self.btn_ml_prediction_open.setText(_translate("MachineLearningPrediction", "Machine Learning Prediction"))
        self.btn_ml_open.setText(_translate("MachineLearningPrediction", "Machine Learning"))
        self.label_13.setText(_translate("MachineLearningPrediction", "Feature Size"))
        self.txt_feature_size.setPlaceholderText(_translate("MachineLearningPrediction", "Feature Size"))
        self.radioCNN.setText(_translate("MachineLearningPrediction", "CNN"))
        self.radioMLP.setText(_translate("MachineLearningPrediction", "MLP"))
        self.btn_prediction_distance_open.setText(_translate("MachineLearningPrediction", "Prediction at Each Distance"))
        self.label_load_3.setText(_translate("MachineLearningPrediction", "Mode"))
