# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PredictionDistance.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1440, 872)
        self.files_frame_2 = QtWidgets.QFrame(Dialog)
        self.files_frame_2.setGeometry(QtCore.QRect(10, 260, 431, 101))
        self.files_frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.files_frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.files_frame_2.setObjectName("files_frame_2")
        self.txt_distance = QtWidgets.QLineEdit(self.files_frame_2)
        self.txt_distance.setGeometry(QtCore.QRect(100, 50, 121, 21))
        self.txt_distance.setText("")
        self.txt_distance.setObjectName("txt_distance")
        self.label_load_6 = QtWidgets.QLabel(self.files_frame_2)
        self.label_load_6.setGeometry(QtCore.QRect(20, 10, 151, 21))
        self.label_load_6.setObjectName("label_load_6")
        self.label_load_7 = QtWidgets.QLabel(self.files_frame_2)
        self.label_load_7.setGeometry(QtCore.QRect(20, 50, 101, 21))
        self.label_load_7.setObjectName("label_load_7")
        self.btn_validation_file = QtWidgets.QPushButton(self.files_frame_2)
        self.btn_validation_file.setGeometry(QtCore.QRect(160, 10, 271, 32))
        self.btn_validation_file.setObjectName("btn_validation_file")
        self.btn_start_prediction = QtWidgets.QPushButton(self.files_frame_2)
        self.btn_start_prediction.setGeometry(QtCore.QRect(240, 50, 131, 32))
        self.btn_start_prediction.setObjectName("btn_start_prediction")
        self.random_forest_frame = QtWidgets.QFrame(Dialog)
        self.random_forest_frame.setGeometry(QtCore.QRect(460, 80, 571, 531))
        self.random_forest_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.random_forest_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.random_forest_frame.setObjectName("random_forest_frame")
        self.label_9 = QtWidgets.QLabel(self.random_forest_frame)
        self.label_9.setGeometry(QtCore.QRect(10, 10, 271, 16))
        self.label_9.setObjectName("label_9")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.random_forest_frame)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(30, 50, 491, 441))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.plot_confusion_matrix = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.plot_confusion_matrix.setContentsMargins(0, 0, 0, 0)
        self.plot_confusion_matrix.setObjectName("plot_confusion_matrix")
        self.label_load_12 = QtWidgets.QLabel(Dialog)
        self.label_load_12.setGeometry(QtCore.QRect(20, 50, 351, 21))
        self.label_load_12.setObjectName("label_load_12")
        self.radioCNN = QtWidgets.QRadioButton(Dialog)
        self.radioCNN.setGeometry(QtCore.QRect(20, 120, 100, 20))
        self.radioCNN.setObjectName("radioCNN")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(20, 90, 91, 16))
        self.label_10.setObjectName("label_10")
        self.radioMLP = QtWidgets.QRadioButton(Dialog)
        self.radioMLP.setGeometry(QtCore.QRect(110, 120, 100, 20))
        self.radioMLP.setObjectName("radioMLP")
        self.files_frame_4 = QtWidgets.QFrame(Dialog)
        self.files_frame_4.setGeometry(QtCore.QRect(20, 150, 401, 101))
        self.files_frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.files_frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.files_frame_4.setObjectName("files_frame_4")
        self.label_load_3 = QtWidgets.QLabel(self.files_frame_4)
        self.label_load_3.setGeometry(QtCore.QRect(20, 20, 81, 16))
        self.label_load_3.setObjectName("label_load_3")
        self.btn_load_model = QtWidgets.QPushButton(self.files_frame_4)
        self.btn_load_model.setGeometry(QtCore.QRect(120, 10, 271, 32))
        self.btn_load_model.setObjectName("btn_load_model")
        self.txt_model_name = QtWidgets.QLineEdit(self.files_frame_4)
        self.txt_model_name.setGeometry(QtCore.QRect(120, 50, 261, 21))
        self.txt_model_name.setObjectName("txt_model_name")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(20, 460, 271, 16))
        self.label_8.setObjectName("label_8")
        self.btn_ml_open = QtWidgets.QPushButton(Dialog)
        self.btn_ml_open.setGeometry(QtCore.QRect(220, 10, 241, 32))
        self.btn_ml_open.setObjectName("btn_ml_open")
        self.btn_prediction_distance_open = QtWidgets.QPushButton(Dialog)
        self.btn_prediction_distance_open.setGeometry(QtCore.QRect(690, 10, 251, 32))
        self.btn_prediction_distance_open.setObjectName("btn_prediction_distance_open")
        self.btn_data_open = QtWidgets.QPushButton(Dialog)
        self.btn_data_open.setGeometry(QtCore.QRect(10, 10, 221, 32))
        self.btn_data_open.setObjectName("btn_data_open")
        self.btn_ml_prediction_open = QtWidgets.QPushButton(Dialog)
        self.btn_ml_prediction_open.setGeometry(QtCore.QRect(450, 10, 251, 32))
        self.btn_ml_prediction_open.setObjectName("btn_ml_prediction_open")
        self.label_13 = QtWidgets.QLabel(Dialog)
        self.label_13.setGeometry(QtCore.QRect(20, 420, 91, 16))
        self.label_13.setObjectName("label_13")
        self.txt_feature_size = QtWidgets.QLineEdit(Dialog)
        self.txt_feature_size.setGeometry(QtCore.QRect(130, 420, 91, 21))
        self.txt_feature_size.setText("")
        self.txt_feature_size.setClearButtonEnabled(False)
        self.txt_feature_size.setObjectName("txt_feature_size")
        self.table_widget = QtWidgets.QTableWidget(Dialog)
        self.table_widget.setGeometry(QtCore.QRect(20, 490, 401, 291))
        self.table_widget.setMinimumSize(QtCore.QSize(401, 0))
        self.table_widget.setMaximumSize(QtCore.QSize(401, 16777215))
        self.table_widget.setObjectName("table_widget")
        self.table_widget.setColumnCount(4)
        self.table_widget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget.setHorizontalHeaderItem(3, item)
        self.label_load_4 = QtWidgets.QLabel(Dialog)
        self.label_load_4.setGeometry(QtCore.QRect(20, 380, 76, 16))
        self.label_load_4.setObjectName("label_load_4")
        self.cb_output = QtWidgets.QComboBox(Dialog)
        self.cb_output.setGeometry(QtCore.QRect(140, 380, 291, 26))
        self.cb_output.setObjectName("cb_output")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_load_6.setText(_translate("Dialog", "Load Validation File"))
        self.label_load_7.setText(_translate("Dialog", "Distance"))
        self.btn_validation_file.setText(_translate("Dialog", "Validation File"))
        self.btn_start_prediction.setText(_translate("Dialog", "Start Prediction"))
        self.label_9.setText(_translate("Dialog", "Confusion Matrix"))
        self.label_load_12.setText(_translate("Dialog", "Prediction at each distance"))
        self.radioCNN.setText(_translate("Dialog", "CNN"))
        self.label_10.setText(_translate("Dialog", "Load Model"))
        self.radioMLP.setText(_translate("Dialog", "MLP"))
        self.label_load_3.setText(_translate("Dialog", "Select Model"))
        self.btn_load_model.setText(_translate("Dialog", "Load Model"))
        self.label_8.setText(_translate("Dialog", "Prediction Table"))
        self.btn_ml_open.setText(_translate("Dialog", "Machine Learning"))
        self.btn_prediction_distance_open.setText(_translate("Dialog", "Prediction at Each Distance"))
        self.btn_data_open.setText(_translate("Dialog", "Data Processing"))
        self.btn_ml_prediction_open.setText(_translate("Dialog", "Machine Learning Prediction"))
        self.label_13.setText(_translate("Dialog", "Feature Size"))
        self.txt_feature_size.setPlaceholderText(_translate("Dialog", "Feature Size"))
        item = self.table_widget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Label"))
        item = self.table_widget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Total"))
        self.label_load_4.setText(_translate("Dialog", "Mode"))
